name: Daily Sigma Alert

on:
  schedule:
    - cron: '0 12 * * *'       # 매일 KST 21시 → UTC 12:00
  workflow_dispatch:

jobs:
  run-sigma-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sigma checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python sigma_buy_checker.py
