name: Daily Sigma Alert

on:
  schedule:
    - cron: '0 11 * * 1-5'       # 매일 KST 20시 → UTC 11:00
  workflow_dispatch:

jobs:
  run-sigma-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sigma checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python sigma_multi.sh
